# configs/dataset/dda.yaml
# 注意：这里不需要 # @package _global_，因为它的内容会自动挂载到 cfg.dataset 下

name: dda
datadir: data/DDA  # 确保这个路径存在
max_nodes: 10
min_nodes: 5
num_subgraphs: 2000     # 正常训练时的数量
# num_bins: 45           # 节点特征分箱
# neg_sample_ratio: 0.8
# ★★★ 核心维度定义 (GAR+ Logic) ★★★
num_node_types: 4  # [Enzyme, Transcription, ..., Other]
num_edge_types: 129   # [NoEdge, Pos/Low, Pos/High, Neg/Low, Neg/High]
# DataModule 需要的基础参数
pin_memory: false
num_workers: 0          # Debug 时设为 0 避免多进程死锁，正常训练可设为 4